minVersion: '0.9.0'
github:
    owner: getsentry
    repo: raven-ruby
changelogPolicy: simple
preReleaseCommand: bash .scripts/bump-version.sh
statusProvider: 
    name: github
targets:
    - name: github
    - name: registry
      type: sdk
      config:
          canonical: 'gem:sentry-raven'
