inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'examples/**/*'
    - 'lib/raven/okjson.rb'
    - 'lib/raven/utils/deep_merge.rb'

Style/SignalException:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
