language: ruby
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change
