language: ruby

rvm:
  - jruby-19mode
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head

gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/railsmaster.gemfile

sudo: false

notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - rvm: jruby-19mode
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails41.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: ree
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: ree
      gemfile: gemfiles/rails41.gemfile
    - rvm: ree
      gemfile: gemfiles/rails40.gemfile
