language: ruby

rvm:
  - jruby-19mode
  - 1.9.3
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile

sudo: false

notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.2.4
      gemfile: gemfiles/rails32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails32.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails5.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails5.gemfile
