language: ruby
sudo: required
dist: trusty

cache:
  bundler: true

bundler_args: --without test --jobs 3 --retry 3

rvm:
  - 1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
  - 2.4.0-preview2

gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile

matrix:
  include:
    - rvm: jruby-1.7.26
      env: JRUBY_OPTS="--dev"
      gemfile: gemfiles/rails42.gemfile
    - rvm: jruby-9.1.5.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
      gemfile: gemfiles/rails42.gemfile
    - rvm: jruby-9.1.5.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
      gemfile: gemfiles/rails5.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.4.0-preview2
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails32.gemfile
    - rvm: 2.4.0-preview2
      gemfile: gemfiles/rails32.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails5.gemfile
  fast_finish: true
